### ISSUE TITLE
problem with one of the input in this code

### ISSUE THREAD

**Issue by mohamadmarjani97** [murtiad/M_HERACLES#1]
hello
i want to use your code to segmentation point clouds but in some of your function used 'normals2'
as an input I want to know how can I calculate this input?
thanks

**Comment by murtiad** [comment]
Hi mohamadmarjani97,
The 'normals2' input is the n-by-3 normal matrix of the input point cloud (n being the number of points in the point cloud). You can compute them using any method, e.g. using Matlab's own pcnormals function (included in the Computer Vision Toolbox) or using 3rd party software like CloudCompare. If you compute it in CloudCompare, you have to save the point cloud in .ply and than declare a variable to get the normals from your point cloud struct... So it should be something like:

`pointCloud = pcread('C:\myPointCloudWithNormals.ply'); 
normals2 = pointCloud.Normal;`

hope this helps and sorry for the late reply (been quite busy!)

arnadi
